modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/sekwah41/Re-Skin/issues"
[[mods]] #mandatory
    modId="reskin"
    version="${file.jarVersion}"
    displayName="Re:Skin"
    updateJSONURL="https://www.sekwah.com/modversions/reskin.json"
    displayURL="https://www.planetminecraft.com/mod/re-skin-4249296/"
    logoFile="reskinlogo.png"
    authors="Sekwah41"
    description='''
    A skin editing mod for role plays, HD skins and whatever you can imagine!
    '''

[[dependencies.reskin]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reskin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
